dist: bionic
language: c

env:
  global:
    - MAKEFLAGS="-j 2"  # parallelize compilation process

matrix:
  include:
    - name: "gcc 10"
      env: MATRIX_ENV="CC=gcc-10 CXX=g++-10"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-10
    - name: "clang 10"
      compiler: clang
      env: MATRIX_ENV="CC=clang-10 CXX=clang++-10"
      addons:
        apt:
          packages:
            - clang-9
    - name: "clang 9"
      compiler: clang
      env: MATRIX_ENV="CC=clang-9 CXX=clang++-9"
      addons:
        apt:
          packages:
            - clang-9
    - name: "clang 8"
      compiler: clang
      env: MATRIX_ENV="CC=clang-8 CXX=clang++-8"
      addons:
        apt:
          packages:
            - clang-8

before_install:
  - eval "${MATRIX_ENV}"

before_script:
  - ./autogen.sh
  - ./configure CPPFLAGS=-Werror
  - grep -i symver config.h

script:
  - make -k
  - ./numactl --show
  - make -k check VERBOSE=1 TESTS='test/distance test/nodemap test/numademo test/tbitmap'
  - make distcheck LOG_COMPILER='sh -c "exit 77"'
